version: "3"

services:
    app:
        build:
            context: .
        ports:
            - "5000"
    nginx:
        image: nginx:latest
        volumes: 
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on: 
            - app
        ports:
            - "80:80"
    mongodb_container:
      image: mongo:latest
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: rootpassword
      ports:
        - 27017:27017
      volumes:
        - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
